image: docker:stable

variables:
  ECR_URI: 637661158709.dkr.ecr.us-east-1.amazonaws.com
  ECR_NAMESPACE: my_images
  IMAGE_NAME: cfn_nag
  AWS_REGION: us-east-1

before_script:
  - apk add --no-cache python py-pip
  - pip install awscli
  - $(aws ecr get-login --no-include-email --region "${AWS_REGION}")

stages:
  - build
  - deploy
  - post

build_image:
  stage: build
  script:
    - docker build --tag $IMAGE_NAME .
    - docker tag $IMAGE_NAME $ECR_URI/$ECR_NAMESPACE/$IMAGE_NAME:latest
  only:
    - master

deploy_image:
  stage: deploy
  script:
    - docker push $ECR_URI/$ECR_NAMESPACE/$IMAGE_NAME:latest
  only:
    - master

post_processing:
  stage: post
  script:
    - docker rmi $ECR_URI/$ECR_NAMESPACE/$IMAGE_NAME:latest
  only:
    - master
