image: [AWS_ACCOUNT].dkr.ecr.us-east-1.amazonaws.com/sandbox_namespace/aws_cli:latest

variables:
  AWS_REGION: us-east-1

stages:
  - test
  - deploy

cfn_test:
  stage: test
  script: |
    aws cloudformation validate-template \
      --template-body file://s3_bucket.yaml \
      --region $AWS_REGION
  only:
    - master

cfn_deploy:
  stage: deploy
  script: |
    aws cloudformation deploy \
      --template-file s3_bucket.yaml \
      --stack-name my-test-bucket-stack \
      --parameter-overrides \
        BucketName=kabirg12345 \
      --tags \
        Type=gitlab-pipeline-test \
      --region $AWS_REGION
  only:
    - master
