image: docker:stable

variables:
  ECR_URI: [ACCOUNT_ID].dkr.ecr.us-east-1.amazonaws.com
  ECR_NAMESPACE: sandbox_namespace
  IMAGE_NAME: aws_cli
  AWS_REGION: us-east-1

before_script:
  - apk add --no-cache python3 py-pip
  - pip install awscli
  - $(aws ecr get-login --no-include-email --region "${AWS_REGION}")

stages:
  - build
  - deploy
  - post

build_image:
  stage: build
  script:
    - docker build --tag $ECR_URI/$ECR_NAMESPACE/$IMAGE_NAME:latest .
  only:
    - master

deploy_image:
  stage: deploy
  script:
    - docker push $ECR_URI/$ECR_NAMESPACE/$IMAGE_NAME:latest
  only:
    - master

post_processing:
  stage: post
  script:
    - docker rmi $ECR_URI/$ECR_NAMESPACE/$IMAGE_NAME:latest
  only:
    - master
